import networkx as nx

from .base import BaseRunner


class BaseParallelRunner(BaseRunner):

    def run(self, task):
        self.create_graph(task)
        self.submit_tasks()
        self.wait_tasks()

    def create_graph(self, task):
        self.graph = graph = nx.DiGraph()
        self.nodetaskmap = nodetaskmap = {}
        self.root = task.get_taskid()

        def creator(t):
            i = t.get_taskid()
            nodetaskmap[i] = t
            for p in t.get_parents():
                k = p.get_taskid()
                graph.add_node(k)
                graph.add_edge(k, i)
                creator(p)

        creator(task)

    def sorted_nodes(self):
        return nx.topological_sort(self.graph)

    def submit_tasks(self):
        """
        Submit tasks using the :attr:`graph` generated by :meth:`create_graph`.
        """
        raise NotImplementedError

    def wait_tasks(self):
        raise NotImplementedError

    @property
    def run_func(self):
        return run_task_load_parents


def run_task_load_parents(task):
    task.pre_run()
    try:
        if task.is_finished():
            task.load()
        else:
            for parent in task.get_parents():
                parent.load()
            task.run()
        task.post_success_run()
    except Exception as e:
        task.post_error_run(e)
        raise
