import itertools

import networkx as nx


# TODO: this is base class now so rename it after...
class MixInParallelRunner(object):

    def run(self, task):
        self.create_graph(task)
        self.submit_tasks()
        self.wait_tasks()

    def create_graph(self, task):
        self.graph = graph = nx.DiGraph()
        self.nodetaskmap = nodetaskmap = {}
        counter = itertools.count().next
        self.root = root = counter()

        def creator(i, t):
            nodetaskmap[i] = t
            for p in t.get_parents():
                k = counter()
                graph.add_node(k)
                graph.add_edge(k, i)
                creator(k, p)

        creator(root, task)

    def sorted_nodes(self):
        return nx.topological_sort(self.graph)

    def submit_tasks(self):
        """
        Submit tasks using the :attr:`graph` generated by :meth:`create_graph`.
        """
        raise NotImplementedError

    def wait_tasks(self):
        raise NotImplementedError

    @property
    def run_func(self):
        return run_task_load_parents


def run_task_load_parents(task):
    task.pre_run()
    try:
        if task.is_finished():
            task.load()
        else:
            for parent in task.get_parents():
                parent.load()
            task.run()
        task.post_success_run()
    except Exception as e:
        task.post_error_run(e)
        raise
